dev:
    cargo watch -x "build --target=wasm32-unknown-unknown && wasm-bindgen target/wasm32-unknown-unknown/debug/engine.wasm --out-dir ../src/lib/wasm"

release:
    cargo build --release --target=wasm32-unknown-unknown
    wasm-bindgen target/wasm32-unknown-unknown/release/engine.wasm --out-dir ../src/lib/wasm
